// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_create_goal_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::create_goal(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_create_goal<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_list_goals_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::list_goals(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_list_goals<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_get_wallets_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::get_wallets(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_get_wallets<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_update_goal_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::update_goal(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_update_goal<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_delete_goal_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::delete_goal(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_delete_goal<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_get_public_goal_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::get_public_goal(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_get_public_goal<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_create_invoice_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::create_invoice(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_create_invoice<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_lnurl_params_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::lnurl_params(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_lnurl_params<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_lnurl_callback_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::lnurl_callback(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_lnurl_callback<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_on_invoice_paid_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::on_invoice_paid(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_invoice_paid<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sweep_goal_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::sweep_goal(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_sweep_goal<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_list_periods_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::list_periods(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_list_periods<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn create_goal(payload: _rt::String) -> _rt::String;
    fn list_goals(payload: _rt::String) -> _rt::String;
    fn get_wallets(payload: _rt::String) -> _rt::String;
    fn update_goal(payload: _rt::String) -> _rt::String;
    fn delete_goal(payload: _rt::String) -> _rt::String;
    fn get_public_goal(payload: _rt::String) -> _rt::String;
    fn create_invoice(payload: _rt::String) -> _rt::String;
    fn lnurl_params(payload: _rt::String) -> _rt::String;
    fn lnurl_callback(payload: _rt::String) -> _rt::String;
    fn on_invoice_paid(payload: _rt::String) -> _rt::String;
    fn sweep_goal(payload: _rt::String) -> _rt::String;
    fn list_periods(payload: _rt::String) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_zapgoals_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "create-goal")] unsafe extern "C" fn
        export_create_goal(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_create_goal_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_create-goal")] unsafe extern "C" fn
        _post_return_create_goal(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_create_goal::<$ty > (arg0) } } #[unsafe (export_name =
        "list-goals")] unsafe extern "C" fn export_list_goals(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_list_goals_cabi::<$ty
        > (arg0, arg1) } } #[unsafe (export_name = "cabi_post_list-goals")] unsafe extern
        "C" fn _post_return_list_goals(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_list_goals::<$ty > (arg0) } } #[unsafe (export_name =
        "get-wallets")] unsafe extern "C" fn export_get_wallets(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_get_wallets_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_get-wallets")] unsafe extern "C" fn _post_return_get_wallets(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_get_wallets::<$ty > (arg0)
        } } #[unsafe (export_name = "update-goal")] unsafe extern "C" fn
        export_update_goal(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_update_goal_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_update-goal")] unsafe extern "C" fn
        _post_return_update_goal(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_update_goal::<$ty > (arg0) } } #[unsafe (export_name =
        "delete-goal")] unsafe extern "C" fn export_delete_goal(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_delete_goal_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_delete-goal")] unsafe extern "C" fn _post_return_delete_goal(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_delete_goal::<$ty > (arg0)
        } } #[unsafe (export_name = "get-public-goal")] unsafe extern "C" fn
        export_get_public_goal(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_get_public_goal_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "cabi_post_get-public-goal")] unsafe extern "C" fn
        _post_return_get_public_goal(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_get_public_goal::<$ty > (arg0) } } #[unsafe (export_name =
        "create-invoice")] unsafe extern "C" fn export_create_invoice(arg0 : * mut u8,
        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_create_invoice_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_create-invoice")] unsafe extern "C" fn
        _post_return_create_invoice(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_create_invoice::<$ty > (arg0) } } #[unsafe (export_name =
        "lnurl-params")] unsafe extern "C" fn export_lnurl_params(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_lnurl_params_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_lnurl-params")] unsafe extern "C" fn _post_return_lnurl_params(arg0 :
        * mut u8,) { unsafe { $($path_to_types)*:: __post_return_lnurl_params::<$ty >
        (arg0) } } #[unsafe (export_name = "lnurl-callback")] unsafe extern "C" fn
        export_lnurl_callback(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_lnurl_callback_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "cabi_post_lnurl-callback")] unsafe extern "C" fn
        _post_return_lnurl_callback(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_lnurl_callback::<$ty > (arg0) } } #[unsafe (export_name =
        "on-invoice-paid")] unsafe extern "C" fn export_on_invoice_paid(arg0 : * mut u8,
        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_on_invoice_paid_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_on-invoice-paid")] unsafe extern "C" fn
        _post_return_on_invoice_paid(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_on_invoice_paid::<$ty > (arg0) } } #[unsafe (export_name =
        "sweep-goal")] unsafe extern "C" fn export_sweep_goal(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_sweep_goal_cabi::<$ty
        > (arg0, arg1) } } #[unsafe (export_name = "cabi_post_sweep-goal")] unsafe extern
        "C" fn _post_return_sweep_goal(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_sweep_goal::<$ty > (arg0) } } #[unsafe (export_name =
        "list-periods")] unsafe extern "C" fn export_list_periods(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_list_periods_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "cabi_post_list-periods")] unsafe extern "C" fn _post_return_list_periods(arg0 :
        * mut u8,) { unsafe { $($path_to_types)*:: __post_return_list_periods::<$ty >
        (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_zapgoals_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod lnbits {
    pub mod extension {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct StorageGetRequest {
                pub table: _rt::String,
                pub id: _rt::String,
            }
            impl ::core::fmt::Debug for StorageGetRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageGetRequest")
                        .field("table", &self.table)
                        .field("id", &self.id)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct StorageGetResponse {
                pub data_json: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for StorageGetResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageGetResponse")
                        .field("data-json", &self.data_json)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct StorageGetPublicRequest {
                pub table: _rt::String,
                pub id: _rt::String,
            }
            impl ::core::fmt::Debug for StorageGetPublicRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageGetPublicRequest")
                        .field("table", &self.table)
                        .field("id", &self.id)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct StorageSetRequest {
                pub table: _rt::String,
                pub data_json: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for StorageSetRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageSetRequest")
                        .field("table", &self.table)
                        .field("data-json", &self.data_json)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct StorageSetResponse {
                pub ok: bool,
            }
            impl ::core::fmt::Debug for StorageSetResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageSetResponse").field("ok", &self.ok).finish()
                }
            }
            #[derive(Clone)]
            pub struct StorageDeleteRequest {
                pub table: _rt::String,
                pub id: _rt::String,
            }
            impl ::core::fmt::Debug for StorageDeleteRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageDeleteRequest")
                        .field("table", &self.table)
                        .field("id", &self.id)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct StorageDeleteResponse {
                pub ok: bool,
            }
            impl ::core::fmt::Debug for StorageDeleteResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StorageDeleteResponse")
                        .field("ok", &self.ok)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct StoragePaginatedRequest {
                pub table: _rt::String,
                pub filters_json: Option<_rt::String>,
                pub search: Option<_rt::String>,
                pub search_fields_json: Option<_rt::String>,
                pub sort_by: Option<_rt::String>,
                pub descending: bool,
                pub limit: u32,
                pub offset: u32,
            }
            impl ::core::fmt::Debug for StoragePaginatedRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StoragePaginatedRequest")
                        .field("table", &self.table)
                        .field("filters-json", &self.filters_json)
                        .field("search", &self.search)
                        .field("search-fields-json", &self.search_fields_json)
                        .field("sort-by", &self.sort_by)
                        .field("descending", &self.descending)
                        .field("limit", &self.limit)
                        .field("offset", &self.offset)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct StoragePaginatedResponse {
                pub rows_json: _rt::String,
                pub total: u32,
            }
            impl ::core::fmt::Debug for StoragePaginatedResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StoragePaginatedResponse")
                        .field("rows-json", &self.rows_json)
                        .field("total", &self.total)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct CreateInvoicePublicRequest {
                pub source_id: _rt::String,
                pub amount: u64,
                pub currency: _rt::String,
                pub memo: _rt::String,
                pub extra_json: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for CreateInvoicePublicRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CreateInvoicePublicRequest")
                        .field("source-id", &self.source_id)
                        .field("amount", &self.amount)
                        .field("currency", &self.currency)
                        .field("memo", &self.memo)
                        .field("extra-json", &self.extra_json)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct CreateInvoiceResponse {
                pub payment_hash: _rt::String,
                pub payment_request: _rt::String,
                pub checking_id: _rt::String,
            }
            impl ::core::fmt::Debug for CreateInvoiceResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CreateInvoiceResponse")
                        .field("payment-hash", &self.payment_hash)
                        .field("payment-request", &self.payment_request)
                        .field("checking-id", &self.checking_id)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct WalletSummary {
                pub id: _rt::String,
                pub name: _rt::String,
                pub currency: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for WalletSummary {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("WalletSummary")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("currency", &self.currency)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ListWalletsResponse {
                pub wallets: _rt::Vec<WalletSummary>,
            }
            impl ::core::fmt::Debug for ListWalletsResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ListWalletsResponse")
                        .field("wallets", &self.wallets)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct NowResponse {
                pub timestamp: u64,
            }
            impl ::core::fmt::Debug for NowResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("NowResponse")
                        .field("timestamp", &self.timestamp)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct RandomIdRequest {
                pub prefix: _rt::String,
            }
            impl ::core::fmt::Debug for RandomIdRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RandomIdRequest")
                        .field("prefix", &self.prefix)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct RandomIdResponse {
                pub id: _rt::String,
            }
            impl ::core::fmt::Debug for RandomIdResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RandomIdResponse").field("id", &self.id).finish()
                }
            }
            #[derive(Clone)]
            pub struct LogRequest {
                pub level: _rt::String,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for LogRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogRequest")
                        .field("level", &self.level)
                        .field("message", &self.message)
                        .finish()
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct LogResponse {
                pub ok: bool,
            }
            impl ::core::fmt::Debug for LogResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogResponse").field("ok", &self.ok).finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn storage_get(req: &StorageGetRequest) -> StorageGetResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let StorageGetRequest { table: table0, id: id0 } = req;
                    let vec1 = table0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = id0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "storage-get"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3)
                    };
                    let l5 = i32::from(*ptr3.add(0).cast::<u8>());
                    let result9 = StorageGetResponse {
                        data_json: match l5 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l6 = *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len8 = l7;
                                    let bytes8 = _rt::Vec::from_raw_parts(
                                        l6.cast(),
                                        len8,
                                        len8,
                                    );
                                    _rt::string_lift(bytes8)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    };
                    result9
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn storage_get_public(
                req: &StorageGetPublicRequest,
            ) -> StorageGetResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let StorageGetPublicRequest { table: table0, id: id0 } = req;
                    let vec1 = table0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = id0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "storage-get-public"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3)
                    };
                    let l5 = i32::from(*ptr3.add(0).cast::<u8>());
                    let result9 = StorageGetResponse {
                        data_json: match l5 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l6 = *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len8 = l7;
                                    let bytes8 = _rt::Vec::from_raw_parts(
                                        l6.cast(),
                                        len8,
                                        len8,
                                    );
                                    _rt::string_lift(bytes8)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    };
                    result9
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn storage_set(req: &StorageSetRequest) -> StorageSetResponse {
                unsafe {
                    let StorageSetRequest { table: table0, data_json: data_json0 } = req;
                    let vec1 = table0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let (result3_0, result3_1, result3_2) = match data_json0 {
                        Some(e) => {
                            let vec2 = e;
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            (1i32, ptr2.cast_mut(), len2)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "storage-set"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import4(
                            ptr1.cast_mut(),
                            len1,
                            result3_0,
                            result3_1,
                            result3_2,
                        )
                    };
                    StorageSetResponse {
                        ok: _rt::bool_lift(ret as u8),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn storage_delete(req: &StorageDeleteRequest) -> StorageDeleteResponse {
                unsafe {
                    let StorageDeleteRequest { table: table0, id: id0 } = req;
                    let vec1 = table0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = id0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "storage-delete"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import3(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2)
                    };
                    StorageDeleteResponse {
                        ok: _rt::bool_lift(ret as u8),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn storage_get_paginated(
                req: &StoragePaginatedRequest,
            ) -> StoragePaginatedResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 8 + 15 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 8
                            + 15 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    let StoragePaginatedRequest {
                        table: table1,
                        filters_json: filters_json1,
                        search: search1,
                        search_fields_json: search_fields_json1,
                        sort_by: sort_by1,
                        descending: descending1,
                        limit: limit1,
                        offset: offset1,
                    } = req;
                    let vec2 = table1;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr0.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    match filters_json1 {
                        Some(e) => {
                            *ptr0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec3 = e;
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            *ptr0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        None => {
                            *ptr0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match search1 {
                        Some(e) => {
                            *ptr0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec4 = e;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *ptr0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        None => {
                            *ptr0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match search_fields_json1 {
                        Some(e) => {
                            *ptr0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec5 = e;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            *ptr0
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        None => {
                            *ptr0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match sort_by1 {
                        Some(e) => {
                            *ptr0
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec6 = e;
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            *ptr0
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                        None => {
                            *ptr0
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    *ptr0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match descending1 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr0
                        .add(4 + 14 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(limit1);
                    *ptr0
                        .add(8 + 14 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(offset1);
                    let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "storage-get-paginated"]
                        fn wit_import8(_: *mut u8, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import8(_: *mut u8, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import8(ptr0, ptr7) };
                    let l9 = *ptr7.add(0).cast::<*mut u8>();
                    let l10 = *ptr7
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len11 = l10;
                    let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);
                    let l12 = *ptr7
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>();
                    let result13 = StoragePaginatedResponse {
                        rows_json: _rt::string_lift(bytes11),
                        total: l12 as u32,
                    };
                    result13
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn create_invoice_public(
                req: &CreateInvoicePublicRequest,
            ) -> CreateInvoiceResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 6 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 6
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let CreateInvoicePublicRequest {
                        source_id: source_id0,
                        amount: amount0,
                        currency: currency0,
                        memo: memo0,
                        extra_json: extra_json0,
                    } = req;
                    let vec1 = source_id0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = currency0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let vec3 = memo0;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    let (result5_0, result5_1, result5_2) = match extra_json0 {
                        Some(e) => {
                            let vec4 = e;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            (1i32, ptr4.cast_mut(), len4)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr6 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "create-invoice-public"]
                        fn wit_import7(
                            _: *mut u8,
                            _: usize,
                            _: i64,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import7(
                        _: *mut u8,
                        _: usize,
                        _: i64,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import7(
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i64(amount0),
                            ptr2.cast_mut(),
                            len2,
                            ptr3.cast_mut(),
                            len3,
                            result5_0,
                            result5_1,
                            result5_2,
                            ptr6,
                        )
                    };
                    let l8 = *ptr6.add(0).cast::<*mut u8>();
                    let l9 = *ptr6
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len10 = l9;
                    let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);
                    let l11 = *ptr6
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l12 = *ptr6
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len13 = l12;
                    let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);
                    let l14 = *ptr6
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l15 = *ptr6
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len16 = l15;
                    let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
                    let result17 = CreateInvoiceResponse {
                        payment_hash: _rt::string_lift(bytes10),
                        payment_request: _rt::string_lift(bytes13),
                        checking_id: _rt::string_lift(bytes16),
                    };
                    result17
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_user_wallets() -> ListWalletsResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "list-user-wallets"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base14 = l2;
                    let len14 = l3;
                    let mut result14 = _rt::Vec::with_capacity(len14);
                    for i in 0..len14 {
                        let base = base14
                            .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                        let e14 = {
                            let l4 = *base.add(0).cast::<*mut u8>();
                            let l5 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            let l7 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len9 = l8;
                            let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                            let l10 = i32::from(
                                *base
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            WalletSummary {
                                id: _rt::string_lift(bytes6),
                                name: _rt::string_lift(bytes9),
                                currency: match l10 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l11 = *base
                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l12 = *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len13 = l12;
                                            let bytes13 = _rt::Vec::from_raw_parts(
                                                l11.cast(),
                                                len13,
                                                len13,
                                            );
                                            _rt::string_lift(bytes13)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result14.push(e14);
                    }
                    _rt::cabi_dealloc(
                        base14,
                        len14 * (7 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result15 = ListWalletsResponse {
                        wallets: result14,
                    };
                    result15
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn now() -> NowResponse {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "now"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    NowResponse {
                        timestamp: ret as u64,
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn random_id(req: &RandomIdRequest) -> RandomIdResponse {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let RandomIdRequest { prefix: prefix0 } = req;
                    let vec1 = prefix0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "random-id"]
                        fn wit_import3(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import3(ptr1.cast_mut(), len1, ptr2) };
                    let l4 = *ptr2.add(0).cast::<*mut u8>();
                    let l5 = *ptr2
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len6 = l5;
                    let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                    let result7 = RandomIdResponse {
                        id: _rt::string_lift(bytes6),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log(req: &LogRequest) -> LogResponse {
                unsafe {
                    let LogRequest { level: level0, message: message0 } = req;
                    let vec1 = level0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = message0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lnbits:extension/host")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import3(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2)
                    };
                    LogResponse {
                        ok: _rt::bool_lift(ret as u8),
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_zapgoals_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_zapgoals_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_zapgoals_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lnbits:extension:zapgoals:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1541] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x86\x0b\x01A\x02\x01\
A\x0f\x01B:\x01r\x02\x05tables\x02ids\x04\0\x13storage-get-request\x03\0\0\x01ks\
\x01r\x01\x09data-json\x02\x04\0\x14storage-get-response\x03\0\x03\x01r\x02\x05t\
ables\x02ids\x04\0\x1astorage-get-public-request\x03\0\x05\x01r\x02\x05tables\x09\
data-json\x02\x04\0\x13storage-set-request\x03\0\x07\x01r\x01\x02ok\x7f\x04\0\x14\
storage-set-response\x03\0\x09\x01r\x02\x05tables\x02ids\x04\0\x16storage-delete\
-request\x03\0\x0b\x01r\x01\x02ok\x7f\x04\0\x17storage-delete-response\x03\0\x0d\
\x01r\x08\x05tables\x0cfilters-json\x02\x06search\x02\x12search-fields-json\x02\x07\
sort-by\x02\x0adescending\x7f\x05limity\x06offsety\x04\0\x19storage-paginated-re\
quest\x03\0\x0f\x01r\x02\x09rows-jsons\x05totaly\x04\0\x1astorage-paginated-resp\
onse\x03\0\x11\x01r\x05\x09source-ids\x06amountw\x08currencys\x04memos\x0aextra-\
json\x02\x04\0\x1dcreate-invoice-public-request\x03\0\x13\x01r\x03\x0cpayment-ha\
shs\x0fpayment-requests\x0bchecking-ids\x04\0\x17create-invoice-response\x03\0\x15\
\x01r\x03\x02ids\x04names\x08currency\x02\x04\0\x0ewallet-summary\x03\0\x17\x01p\
\x18\x01r\x01\x07wallets\x19\x04\0\x15list-wallets-response\x03\0\x1a\x01r\x01\x09\
timestampw\x04\0\x0cnow-response\x03\0\x1c\x01r\x01\x06prefixs\x04\0\x11random-i\
d-request\x03\0\x1e\x01r\x01\x02ids\x04\0\x12random-id-response\x03\0\x20\x01r\x02\
\x05levels\x07messages\x04\0\x0blog-request\x03\0\"\x01r\x01\x02ok\x7f\x04\0\x0c\
log-response\x03\0$\x01@\x01\x03req\x01\0\x04\x04\0\x0bstorage-get\x01&\x01@\x01\
\x03req\x06\0\x04\x04\0\x12storage-get-public\x01'\x01@\x01\x03req\x08\0\x0a\x04\
\0\x0bstorage-set\x01(\x01@\x01\x03req\x0c\0\x0e\x04\0\x0estorage-delete\x01)\x01\
@\x01\x03req\x10\0\x12\x04\0\x15storage-get-paginated\x01*\x01@\x01\x03req\x14\0\
\x16\x04\0\x15create-invoice-public\x01+\x01@\0\0\x1b\x04\0\x11list-user-wallets\
\x01,\x01@\0\0\x1d\x04\0\x03now\x01-\x01@\x01\x03req\x1f\0!\x04\0\x09random-id\x01\
.\x01@\x01\x03req#\0%\x04\0\x03log\x01/\x03\0\x15lnbits:extension/host\x05\0\x01\
@\x01\x07payloads\0s\x04\0\x0bcreate-goal\x01\x01\x04\0\x0alist-goals\x01\x01\x04\
\0\x0bget-wallets\x01\x01\x04\0\x0bupdate-goal\x01\x01\x04\0\x0bdelete-goal\x01\x01\
\x04\0\x0fget-public-goal\x01\x01\x04\0\x0ecreate-invoice\x01\x01\x04\0\x0clnurl\
-params\x01\x01\x04\0\x0elnurl-callback\x01\x01\x04\0\x0fon-invoice-paid\x01\x01\
\x04\0\x0asweep-goal\x01\x01\x04\0\x0clist-periods\x01\x01\x04\0\x19lnbits:exten\
sion/zapgoals\x04\0\x0b\x0e\x01\0\x08zapgoals\x03\0\0\0G\x09producers\x01\x0cpro\
cessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
